<?xml version="1.0" encoding="UTF-8" ?>
<Package name="guess-0.0.1" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="emotion" xar="behavior.xar" />
        <BehaviorDescription name="behavior" src="gage" xar="behavior.xar" />
        <BehaviorDescription name="behavior" src="." xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs />
    <Resources>
        <File name="icon" src="icon.png" />
        <File name="app" src="html/app.css" />
        <File name="app" src="html/app.js" />
        <File name="index" src="html/index.html" />
        <File name="robotutils" src="html/bower_components/robotutils.js" />
        <File name="robotutils.min" src="html/bower_components/robotutils.min.js" />
        <File name="videoutils" src="html/bower_components/videoutils.js" />
        <File name="videoutils.min" src="html/bower_components/videoutils.min.js" />
        <File name=".bower" src="html/bower_components/angular/.bower.json" />
        <File name="angular-csp" src="html/bower_components/angular/angular-csp.css" />
        <File name="angular" src="html/bower_components/angular/angular.js" />
        <File name="angular.min" src="html/bower_components/angular/angular.min.js" />
        <File name="angular.min.js" src="html/bower_components/angular/angular.min.js.gzip" />
        <File name="angular.min.js" src="html/bower_components/angular/angular.min.js.map" />
        <File name="bower" src="html/bower_components/angular/bower.json" />
        <File name="index" src="html/bower_components/angular/index.js" />
        <File name="LICENSE" src="html/bower_components/angular/LICENSE.md" />
        <File name="package" src="html/bower_components/angular/package.json" />
        <File name="README" src="html/bower_components/angular/README.md" />
        <File name=".bower" src="html/bower_components/angular-loader/.bower.json" />
        <File name="angular-loader" src="html/bower_components/angular-loader/angular-loader.js" />
        <File name="angular-loader.min" src="html/bower_components/angular-loader/angular-loader.min.js" />
        <File name="angular-loader.min.js" src="html/bower_components/angular-loader/angular-loader.min.js.map" />
        <File name="bower" src="html/bower_components/angular-loader/bower.json" />
        <File name="LICENSE" src="html/bower_components/angular-loader/LICENSE.md" />
        <File name="package" src="html/bower_components/angular-loader/package.json" />
        <File name="README" src="html/bower_components/angular-loader/README.md" />
        <File name=".bower" src="html/bower_components/angular-mocks/.bower.json" />
        <File name="angular-mocks" src="html/bower_components/angular-mocks/angular-mocks.js" />
        <File name="bower" src="html/bower_components/angular-mocks/bower.json" />
        <File name="LICENSE" src="html/bower_components/angular-mocks/LICENSE.md" />
        <File name="ngAnimateMock" src="html/bower_components/angular-mocks/ngAnimateMock.js" />
        <File name="ngMock" src="html/bower_components/angular-mocks/ngMock.js" />
        <File name="ngMockE2E" src="html/bower_components/angular-mocks/ngMockE2E.js" />
        <File name="package" src="html/bower_components/angular-mocks/package.json" />
        <File name="README" src="html/bower_components/angular-mocks/README.md" />
        <File name=".bower" src="html/bower_components/angular-route/.bower.json" />
        <File name="angular-route" src="html/bower_components/angular-route/angular-route.js" />
        <File name="angular-route.min" src="html/bower_components/angular-route/angular-route.min.js" />
        <File name="angular-route.min.js" src="html/bower_components/angular-route/angular-route.min.js.map" />
        <File name="bower" src="html/bower_components/angular-route/bower.json" />
        <File name="index" src="html/bower_components/angular-route/index.js" />
        <File name="LICENSE" src="html/bower_components/angular-route/LICENSE.md" />
        <File name="package" src="html/bower_components/angular-route/package.json" />
        <File name="README" src="html/bower_components/angular-route/README.md" />
        <File name=".bower" src="html/bower_components/jquery/.bower.json" />
        <File name="AUTHORS" src="html/bower_components/jquery/AUTHORS.txt" />
        <File name="bower" src="html/bower_components/jquery/bower.json" />
        <File name="LICENSE" src="html/bower_components/jquery/LICENSE.txt" />
        <File name="README" src="html/bower_components/jquery/README.md" />
        <File name="jquery" src="html/bower_components/jquery/dist/jquery.js" />
        <File name="jquery.min" src="html/bower_components/jquery/dist/jquery.min.js" />
        <File name="jquery.min" src="html/bower_components/jquery/dist/jquery.min.map" />
        <File name="LICENSE" src="html/bower_components/jquery/external/sizzle/LICENSE.txt" />
        <File name="sizzle" src="html/bower_components/jquery/external/sizzle/dist/sizzle.js" />
        <File name="sizzle.min" src="html/bower_components/jquery/external/sizzle/dist/sizzle.min.js" />
        <File name="sizzle.min" src="html/bower_components/jquery/external/sizzle/dist/sizzle.min.map" />
        <File name="" src="html/bower_components/jquery/src/.jshintrc" />
        <File name="ajax" src="html/bower_components/jquery/src/ajax.js" />
        <File name="attributes" src="html/bower_components/jquery/src/attributes.js" />
        <File name="callbacks" src="html/bower_components/jquery/src/callbacks.js" />
        <File name="core" src="html/bower_components/jquery/src/core.js" />
        <File name="css" src="html/bower_components/jquery/src/css.js" />
        <File name="data" src="html/bower_components/jquery/src/data.js" />
        <File name="deferred" src="html/bower_components/jquery/src/deferred.js" />
        <File name="deprecated" src="html/bower_components/jquery/src/deprecated.js" />
        <File name="dimensions" src="html/bower_components/jquery/src/dimensions.js" />
        <File name="effects" src="html/bower_components/jquery/src/effects.js" />
        <File name="event" src="html/bower_components/jquery/src/event.js" />
        <File name="intro" src="html/bower_components/jquery/src/intro.js" />
        <File name="jquery" src="html/bower_components/jquery/src/jquery.js" />
        <File name="manipulation" src="html/bower_components/jquery/src/manipulation.js" />
        <File name="offset" src="html/bower_components/jquery/src/offset.js" />
        <File name="outro" src="html/bower_components/jquery/src/outro.js" />
        <File name="queue" src="html/bower_components/jquery/src/queue.js" />
        <File name="selector-native" src="html/bower_components/jquery/src/selector-native.js" />
        <File name="selector-sizzle" src="html/bower_components/jquery/src/selector-sizzle.js" />
        <File name="selector" src="html/bower_components/jquery/src/selector.js" />
        <File name="serialize" src="html/bower_components/jquery/src/serialize.js" />
        <File name="traversing" src="html/bower_components/jquery/src/traversing.js" />
        <File name="wrap" src="html/bower_components/jquery/src/wrap.js" />
        <File name="jsonp" src="html/bower_components/jquery/src/ajax/jsonp.js" />
        <File name="load" src="html/bower_components/jquery/src/ajax/load.js" />
        <File name="parseJSON" src="html/bower_components/jquery/src/ajax/parseJSON.js" />
        <File name="parseXML" src="html/bower_components/jquery/src/ajax/parseXML.js" />
        <File name="script" src="html/bower_components/jquery/src/ajax/script.js" />
        <File name="xhr" src="html/bower_components/jquery/src/ajax/xhr.js" />
        <File name="location" src="html/bower_components/jquery/src/ajax/var/location.js" />
        <File name="nonce" src="html/bower_components/jquery/src/ajax/var/nonce.js" />
        <File name="rquery" src="html/bower_components/jquery/src/ajax/var/rquery.js" />
        <File name="attr" src="html/bower_components/jquery/src/attributes/attr.js" />
        <File name="classes" src="html/bower_components/jquery/src/attributes/classes.js" />
        <File name="prop" src="html/bower_components/jquery/src/attributes/prop.js" />
        <File name="support" src="html/bower_components/jquery/src/attributes/support.js" />
        <File name="val" src="html/bower_components/jquery/src/attributes/val.js" />
        <File name="access" src="html/bower_components/jquery/src/core/access.js" />
        <File name="init" src="html/bower_components/jquery/src/core/init.js" />
        <File name="parseHTML" src="html/bower_components/jquery/src/core/parseHTML.js" />
        <File name="ready" src="html/bower_components/jquery/src/core/ready.js" />
        <File name="rsingleTag" src="html/bower_components/jquery/src/core/var/rsingleTag.js" />
        <File name="addGetHookIf" src="html/bower_components/jquery/src/css/addGetHookIf.js" />
        <File name="adjustCSS" src="html/bower_components/jquery/src/css/adjustCSS.js" />
        <File name="curCSS" src="html/bower_components/jquery/src/css/curCSS.js" />
        <File name="defaultDisplay" src="html/bower_components/jquery/src/css/defaultDisplay.js" />
        <File name="hiddenVisibleSelectors" src="html/bower_components/jquery/src/css/hiddenVisibleSelectors.js" />
        <File name="showHide" src="html/bower_components/jquery/src/css/showHide.js" />
        <File name="support" src="html/bower_components/jquery/src/css/support.js" />
        <File name="cssExpand" src="html/bower_components/jquery/src/css/var/cssExpand.js" />
        <File name="getStyles" src="html/bower_components/jquery/src/css/var/getStyles.js" />
        <File name="isHidden" src="html/bower_components/jquery/src/css/var/isHidden.js" />
        <File name="rmargin" src="html/bower_components/jquery/src/css/var/rmargin.js" />
        <File name="rnumnonpx" src="html/bower_components/jquery/src/css/var/rnumnonpx.js" />
        <File name="swap" src="html/bower_components/jquery/src/css/var/swap.js" />
        <File name="Data" src="html/bower_components/jquery/src/data/Data.js" />
        <File name="acceptData" src="html/bower_components/jquery/src/data/var/acceptData.js" />
        <File name="dataPriv" src="html/bower_components/jquery/src/data/var/dataPriv.js" />
        <File name="dataUser" src="html/bower_components/jquery/src/data/var/dataUser.js" />
        <File name="animatedSelector" src="html/bower_components/jquery/src/effects/animatedSelector.js" />
        <File name="Tween" src="html/bower_components/jquery/src/effects/Tween.js" />
        <File name="ajax" src="html/bower_components/jquery/src/event/ajax.js" />
        <File name="alias" src="html/bower_components/jquery/src/event/alias.js" />
        <File name="focusin" src="html/bower_components/jquery/src/event/focusin.js" />
        <File name="support" src="html/bower_components/jquery/src/event/support.js" />
        <File name="trigger" src="html/bower_components/jquery/src/event/trigger.js" />
        <File name="amd" src="html/bower_components/jquery/src/exports/amd.js" />
        <File name="global" src="html/bower_components/jquery/src/exports/global.js" />
        <File name="_evalUrl" src="html/bower_components/jquery/src/manipulation/_evalUrl.js" />
        <File name="buildFragment" src="html/bower_components/jquery/src/manipulation/buildFragment.js" />
        <File name="getAll" src="html/bower_components/jquery/src/manipulation/getAll.js" />
        <File name="setGlobalEval" src="html/bower_components/jquery/src/manipulation/setGlobalEval.js" />
        <File name="support" src="html/bower_components/jquery/src/manipulation/support.js" />
        <File name="wrapMap" src="html/bower_components/jquery/src/manipulation/wrapMap.js" />
        <File name="rcheckableType" src="html/bower_components/jquery/src/manipulation/var/rcheckableType.js" />
        <File name="rscriptType" src="html/bower_components/jquery/src/manipulation/var/rscriptType.js" />
        <File name="rtagName" src="html/bower_components/jquery/src/manipulation/var/rtagName.js" />
        <File name="delay" src="html/bower_components/jquery/src/queue/delay.js" />
        <File name="findFilter" src="html/bower_components/jquery/src/traversing/findFilter.js" />
        <File name="dir" src="html/bower_components/jquery/src/traversing/var/dir.js" />
        <File name="rneedsContext" src="html/bower_components/jquery/src/traversing/var/rneedsContext.js" />
        <File name="siblings" src="html/bower_components/jquery/src/traversing/var/siblings.js" />
        <File name="arr" src="html/bower_components/jquery/src/var/arr.js" />
        <File name="class2type" src="html/bower_components/jquery/src/var/class2type.js" />
        <File name="concat" src="html/bower_components/jquery/src/var/concat.js" />
        <File name="document" src="html/bower_components/jquery/src/var/document.js" />
        <File name="documentElement" src="html/bower_components/jquery/src/var/documentElement.js" />
        <File name="hasOwn" src="html/bower_components/jquery/src/var/hasOwn.js" />
        <File name="indexOf" src="html/bower_components/jquery/src/var/indexOf.js" />
        <File name="pnum" src="html/bower_components/jquery/src/var/pnum.js" />
        <File name="push" src="html/bower_components/jquery/src/var/push.js" />
        <File name="rcssNum" src="html/bower_components/jquery/src/var/rcssNum.js" />
        <File name="rnotwhite" src="html/bower_components/jquery/src/var/rnotwhite.js" />
        <File name="slice" src="html/bower_components/jquery/src/var/slice.js" />
        <File name="support" src="html/bower_components/jquery/src/var/support.js" />
        <File name="toString" src="html/bower_components/jquery/src/var/toString.js" />
        <File name="game" src="html/game/game.html" />
        <File name="game" src="html/game/game.js" />
        <File name="age" src="html/img/age.png" />
        <File name="background" src="html/img/background.jpg" />
        <File name="face" src="html/img/face.jpg" />
        <File name="gender" src="html/img/gender.png" />
        <File name="home" src="html/img/home.png" />
        <File name="Pepper-white" src="html/img/Pepper-white.png" />
        <File name="" src="html/semantic/.versions" />
        <File name="LICENSE" src="html/semantic/LICENSE" />
        <File name="package" src="html/semantic/package.js" />
        <File name="package" src="html/semantic/package.json" />
        <File name="README" src="html/semantic/README.md" />
        <File name="semantic" src="html/semantic/semantic.css" />
        <File name="semantic" src="html/semantic/semantic.js" />
        <File name="semantic.min" src="html/semantic/semantic.min.css" />
        <File name="semantic.min" src="html/semantic/semantic.min.js" />
        <File name="accordion" src="html/semantic/components/accordion.css" />
        <File name="accordion" src="html/semantic/components/accordion.js" />
        <File name="accordion.min" src="html/semantic/components/accordion.min.css" />
        <File name="accordion.min" src="html/semantic/components/accordion.min.js" />
        <File name="ad" src="html/semantic/components/ad.css" />
        <File name="ad.min" src="html/semantic/components/ad.min.css" />
        <File name="api" src="html/semantic/components/api.js" />
        <File name="api.min" src="html/semantic/components/api.min.js" />
        <File name="breadcrumb" src="html/semantic/components/breadcrumb.css" />
        <File name="breadcrumb.min" src="html/semantic/components/breadcrumb.min.css" />
        <File name="button" src="html/semantic/components/button.css" />
        <File name="button.min" src="html/semantic/components/button.min.css" />
        <File name="card" src="html/semantic/components/card.css" />
        <File name="card.min" src="html/semantic/components/card.min.css" />
        <File name="checkbox" src="html/semantic/components/checkbox.css" />
        <File name="checkbox" src="html/semantic/components/checkbox.js" />
        <File name="checkbox.min" src="html/semantic/components/checkbox.min.css" />
        <File name="checkbox.min" src="html/semantic/components/checkbox.min.js" />
        <File name="colorize" src="html/semantic/components/colorize.js" />
        <File name="colorize.min" src="html/semantic/components/colorize.min.js" />
        <File name="comment" src="html/semantic/components/comment.css" />
        <File name="comment.min" src="html/semantic/components/comment.min.css" />
        <File name="container" src="html/semantic/components/container.css" />
        <File name="container.min" src="html/semantic/components/container.min.css" />
        <File name="dimmer" src="html/semantic/components/dimmer.css" />
        <File name="dimmer" src="html/semantic/components/dimmer.js" />
        <File name="dimmer.min" src="html/semantic/components/dimmer.min.css" />
        <File name="dimmer.min" src="html/semantic/components/dimmer.min.js" />
        <File name="divider" src="html/semantic/components/divider.css" />
        <File name="divider.min" src="html/semantic/components/divider.min.css" />
        <File name="dropdown" src="html/semantic/components/dropdown.css" />
        <File name="dropdown" src="html/semantic/components/dropdown.js" />
        <File name="dropdown.min" src="html/semantic/components/dropdown.min.css" />
        <File name="dropdown.min" src="html/semantic/components/dropdown.min.js" />
        <File name="embed" src="html/semantic/components/embed.css" />
        <File name="embed" src="html/semantic/components/embed.js" />
        <File name="embed.min" src="html/semantic/components/embed.min.css" />
        <File name="embed.min" src="html/semantic/components/embed.min.js" />
        <File name="feed" src="html/semantic/components/feed.css" />
        <File name="feed.min" src="html/semantic/components/feed.min.css" />
        <File name="flag" src="html/semantic/components/flag.css" />
        <File name="flag.min" src="html/semantic/components/flag.min.css" />
        <File name="form" src="html/semantic/components/form.css" />
        <File name="form" src="html/semantic/components/form.js" />
        <File name="form.min" src="html/semantic/components/form.min.css" />
        <File name="form.min" src="html/semantic/components/form.min.js" />
        <File name="grid" src="html/semantic/components/grid.css" />
        <File name="grid.min" src="html/semantic/components/grid.min.css" />
        <File name="header" src="html/semantic/components/header.css" />
        <File name="header.min" src="html/semantic/components/header.min.css" />
        <File name="icon" src="html/semantic/components/icon.css" />
        <File name="icon.min" src="html/semantic/components/icon.min.css" />
        <File name="image" src="html/semantic/components/image.css" />
        <File name="image.min" src="html/semantic/components/image.min.css" />
        <File name="input" src="html/semantic/components/input.css" />
        <File name="input.min" src="html/semantic/components/input.min.css" />
        <File name="item" src="html/semantic/components/item.css" />
        <File name="item.min" src="html/semantic/components/item.min.css" />
        <File name="label" src="html/semantic/components/label.css" />
        <File name="label.min" src="html/semantic/components/label.min.css" />
        <File name="list" src="html/semantic/components/list.css" />
        <File name="list.min" src="html/semantic/components/list.min.css" />
        <File name="loader" src="html/semantic/components/loader.css" />
        <File name="loader.min" src="html/semantic/components/loader.min.css" />
        <File name="menu" src="html/semantic/components/menu.css" />
        <File name="menu.min" src="html/semantic/components/menu.min.css" />
        <File name="message" src="html/semantic/components/message.css" />
        <File name="message.min" src="html/semantic/components/message.min.css" />
        <File name="modal" src="html/semantic/components/modal.css" />
        <File name="modal" src="html/semantic/components/modal.js" />
        <File name="modal.min" src="html/semantic/components/modal.min.css" />
        <File name="modal.min" src="html/semantic/components/modal.min.js" />
        <File name="nag" src="html/semantic/components/nag.css" />
        <File name="nag" src="html/semantic/components/nag.js" />
        <File name="nag.min" src="html/semantic/components/nag.min.css" />
        <File name="nag.min" src="html/semantic/components/nag.min.js" />
        <File name="popup" src="html/semantic/components/popup.css" />
        <File name="popup" src="html/semantic/components/popup.js" />
        <File name="popup.min" src="html/semantic/components/popup.min.css" />
        <File name="popup.min" src="html/semantic/components/popup.min.js" />
        <File name="progress" src="html/semantic/components/progress.css" />
        <File name="progress" src="html/semantic/components/progress.js" />
        <File name="progress.min" src="html/semantic/components/progress.min.css" />
        <File name="progress.min" src="html/semantic/components/progress.min.js" />
        <File name="rail" src="html/semantic/components/rail.css" />
        <File name="rail.min" src="html/semantic/components/rail.min.css" />
        <File name="rating" src="html/semantic/components/rating.css" />
        <File name="rating" src="html/semantic/components/rating.js" />
        <File name="rating.min" src="html/semantic/components/rating.min.css" />
        <File name="rating.min" src="html/semantic/components/rating.min.js" />
        <File name="reset" src="html/semantic/components/reset.css" />
        <File name="reset.min" src="html/semantic/components/reset.min.css" />
        <File name="reveal" src="html/semantic/components/reveal.css" />
        <File name="reveal.min" src="html/semantic/components/reveal.min.css" />
        <File name="search" src="html/semantic/components/search.css" />
        <File name="search" src="html/semantic/components/search.js" />
        <File name="search.min" src="html/semantic/components/search.min.css" />
        <File name="search.min" src="html/semantic/components/search.min.js" />
        <File name="segment" src="html/semantic/components/segment.css" />
        <File name="segment.min" src="html/semantic/components/segment.min.css" />
        <File name="shape" src="html/semantic/components/shape.css" />
        <File name="shape" src="html/semantic/components/shape.js" />
        <File name="shape.min" src="html/semantic/components/shape.min.css" />
        <File name="shape.min" src="html/semantic/components/shape.min.js" />
        <File name="sidebar" src="html/semantic/components/sidebar.css" />
        <File name="sidebar" src="html/semantic/components/sidebar.js" />
        <File name="sidebar.min" src="html/semantic/components/sidebar.min.css" />
        <File name="sidebar.min" src="html/semantic/components/sidebar.min.js" />
        <File name="site" src="html/semantic/components/site.css" />
        <File name="site" src="html/semantic/components/site.js" />
        <File name="site.min" src="html/semantic/components/site.min.css" />
        <File name="site.min" src="html/semantic/components/site.min.js" />
        <File name="state" src="html/semantic/components/state.js" />
        <File name="state.min" src="html/semantic/components/state.min.js" />
        <File name="statistic" src="html/semantic/components/statistic.css" />
        <File name="statistic.min" src="html/semantic/components/statistic.min.css" />
        <File name="step" src="html/semantic/components/step.css" />
        <File name="step.min" src="html/semantic/components/step.min.css" />
        <File name="sticky" src="html/semantic/components/sticky.css" />
        <File name="sticky" src="html/semantic/components/sticky.js" />
        <File name="sticky.min" src="html/semantic/components/sticky.min.css" />
        <File name="sticky.min" src="html/semantic/components/sticky.min.js" />
        <File name="tab" src="html/semantic/components/tab.css" />
        <File name="tab" src="html/semantic/components/tab.js" />
        <File name="tab.min" src="html/semantic/components/tab.min.css" />
        <File name="tab.min" src="html/semantic/components/tab.min.js" />
        <File name="table" src="html/semantic/components/table.css" />
        <File name="table.min" src="html/semantic/components/table.min.css" />
        <File name="transition" src="html/semantic/components/transition.css" />
        <File name="transition" src="html/semantic/components/transition.js" />
        <File name="transition.min" src="html/semantic/components/transition.min.css" />
        <File name="transition.min" src="html/semantic/components/transition.min.js" />
        <File name="video" src="html/semantic/components/video.css" />
        <File name="video" src="html/semantic/components/video.js" />
        <File name="video.min" src="html/semantic/components/video.min.css" />
        <File name="video.min" src="html/semantic/components/video.min.js" />
        <File name="visibility" src="html/semantic/components/visibility.js" />
        <File name="visibility.min" src="html/semantic/components/visibility.min.js" />
        <File name="visit" src="html/semantic/components/visit.js" />
        <File name="visit.min" src="html/semantic/components/visit.min.js" />
        <File name="icons" src="html/semantic/themes/default/assets/fonts/icons.eot" />
        <File name="icons" src="html/semantic/themes/default/assets/fonts/icons.otf" />
        <File name="icons" src="html/semantic/themes/default/assets/fonts/icons.svg" />
        <File name="icons" src="html/semantic/themes/default/assets/fonts/icons.ttf" />
        <File name="icons" src="html/semantic/themes/default/assets/fonts/icons.woff" />
        <File name="icons" src="html/semantic/themes/default/assets/fonts/icons.woff2" />
        <File name="flags" src="html/semantic/themes/default/assets/images/flags.png" />
        <File name="view1" src="html/view1/view1.html" />
        <File name="view1" src="html/view1/view1.js" />
        <File name="view2" src="html/view2/view2.html" />
        <File name="view2" src="html/view2/view2.js" />
        <File name="translation_en_US" src="translations/translation_en_US.qm" />
        <File name="translation_zh_CN" src="translations/translation_zh_CN.qm" />
    </Resources>
    <Topics />
    <IgnoredPaths />
    <Translations auto-fill="en_US">
        <Translation name="translation_en_US" src="translations/translation_en_US.ts" language="en_US" />
        <Translation name="translation_zh_CN" src="translations/translation_zh_CN.ts" language="zh_CN" />
    </Translations>
</Package>
